spring:
  application:
    name: '@project.name@'
  profiles:
    active: local
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always