server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: congressoModule
          uri: lb://ATOMCONGRESSO
          predicates:
            - Path=/atomcongresso/**
        - id: fichaModule
          uri: lb://ATOMFICHA
          predicates:
            - Path=/atomficha/**
    config:
      import-check:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/